name: simple_connectivity_null_safe
description: Flutter plugin for discovering the state of the network (WiFi &
  mobile/cellular) connectivity on Android and iOS.
homepage: https://github.com/alexverbitsky/simple_connectivity_null_safe
version: 2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.connectivity
        pluginClass: ConnectivityPlugin
      ios:
        pluginClass: FLTConnectivityPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.7.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0 <3.0.0"
